# Generated by Django 4.0.6 on 2022-08-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_generator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyQRCode',
        ),
    ]
